/** Fixed taxonomy for the index. Seeded idempotently; safe to re-run. */
export const CATEGORY_SEED: { slug: string; name: string; blurb: string }[] = [
  { slug: "platforms", name: "AI Platforms & Workbenches", blurb: "Full tax AI assistants, copilots, and workpaper workbenches." },
  { slug: "agent-skills", name: "Agent Skills & Plugins", blurb: "Skill packs, plugins, and portable workflows for AI agents." },
  { slug: "mcp-servers", name: "MCP Servers", blurb: "Model Context Protocol servers exposing tax data and tools." },
  { slug: "tax-prep-filing", name: "Tax Prep & Filing", blurb: "Preparing and e-filing individual and business tax returns." },
  { slug: "vat-gst", name: "VAT, GST & Sales Tax", blurb: "Indirect tax: rates, number validation, calculation, and returns." },
  { slug: "invoicing", name: "Invoicing & E-Invoicing", blurb: "Compliant invoices: Peppol, UBL, ZUGFeRD/Factur-X, and clearance." },
  { slug: "payroll", name: "Payroll & Withholding", blurb: "Payroll taxes, social contributions, and withholding calculation." },
  { slug: "accounting", name: "Accounting & Bookkeeping", blurb: "Ledgers, ERPs, and bookkeeping tools with tax features built in." },
  { slug: "tax-engines", name: "Tax Calculators & Engines", blurb: "Libraries and engines that compute tax, embeddable anywhere." },
  { slug: "rules-as-code", name: "Rules as Code", blurb: "Tax law as executable code: statutes and benefit rules you can run." },
  { slug: "tax-data", name: "Tax Data & Statutes", blurb: "Scrapers, APIs, and corpora of tax law, rulings, rates, and forms." },
  { slug: "tax-ai", name: "Tax AI & NLP", blurb: "Models, pipelines, and applications for tax language." },
  { slug: "rag-retrieval", name: "Retrieval & RAG", blurb: "Embeddings, retrieval pipelines, and RAG over tax corpora." },
  { slug: "compliance", name: "Compliance & Reporting", blurb: "Regulatory filings and standards: SAF-T, CbC, DAC7, FATCA/CRS." },
  { slug: "transfer-pricing", name: "Transfer Pricing & International", blurb: "Cross-border taxation, treaties, and transfer pricing tooling." },
  { slug: "crypto-gains", name: "Crypto & Capital Gains", blurb: "Crypto tax, portfolio accounting, and capital gains calculators." },
  { slug: "policy-microsim", name: "Policy & Microsimulation", blurb: "Tax-benefit microsimulation and policy analysis models." },
  { slug: "local-ai", name: "Local AI", blurb: "AI that runs on your own machine. No cloud, no data leaving the building." },
  { slug: "benchmarks-datasets", name: "Benchmarks & Datasets", blurb: "Evaluation suites and datasets for tax-domain systems." },
  { slug: "curated-lists", name: "Curated Lists", blurb: "Awesome lists and landscape maps of the tax tech ecosystem." },
];
